// <auto-generated />
using System;
using ContabilidadHogar.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContabilidadHogar.Database.Migrations
{
    [DbContext(typeof(ContextMoney))]
    [Migration("20220630012534_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ContabilidadHogar.Models.MoneyControl", b =>
                {
                    b.Property<Guid>("IdTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("AmountTransaction")
                        .HasColumnType("float");

                    b.Property<double>("BalanceTransaction")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IncomeTransaction")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTransaction");

                    b.ToTable("RegistryMoneyControl");
                });
#pragma warning restore 612, 618
        }
    }
}
